# Generated by Django 4.1.1 on 2023-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=150)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
